server:
  port: ${PORT:0}

spring:
  application:
    name: hystrix-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

text:
  greeting: Hello Hystrix Service

name: Babu

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"